### ISSUE TITLE
module 'PySide2.QtGui' has no attribute 'QApplication'

### ISSUE THREAD

**Issue by JYS997760473** [oleschum/radar_scenes#10]
my python version is 3.7.7 and when I run the project, the terminal says that module 'PySide2.QtGui' has no attribute 'QApplication'

**Comment by binjiaqm** [comment]
I saw the same issue now.

Traceback (most recent call last):
  File "/home/xm/.virtualenvs/radar_scenes/bin/rad_viewer", line 11, in <module>
    load_entry_point('radar-scenes==1.0.2', 'gui_scripts', 'rad_viewer')()
  File "/home/xm/.virtualenvs/radar_scenes/lib/python3.8/site-packages/radar_scenes/viewer.py", line 1054, in main
    window.load_sequence(args.filename)
  File "/home/xm/.virtualenvs/radar_scenes/lib/python3.8/site-packages/radar_scenes/viewer.py", line 474, in load_sequence
    QtGui.QApplication.setOverrideCursor(QtCore.Qt.WaitCursor)
AttributeError: module 'PySide2.QtGui' has no attribute 'QApplication'
QThread: Destroyed while thread is still running
Aborted (core dumped)
